### ISSUE TITLE
TODO: Implement Users

### ISSUE THREAD

**Issue by DeadSuperHero** [DeadSuperHero/postmodern#3]
- [ ] Implement login / authentication
- [ ] Set up attributes (Proper Name, Username, Description, Avatar)
- [ ] Ensure that articles get associated to their authors
- [ ] Ensure that one has to be an authenticated user to write an article
